# Header
menu:
  Home: /
  Nota Fiscal: /invoices.html
  Determinação de Impostos: /calculation.html
  Obrigações: /compliance.html
  Documentos: /documents.html
  Monitoramento: /monitor.html

# Logo Image Source
logo_src: /images/favicon.svg
favicon_src: /images/favicon.svg

# Theme Main Subtitle
subtitle_main: Portal dos desenvolvedores da Avalara Brazil

# Theme Secondary subtitle
susbtitle_secondary: Documentações em geral, APIs, how-to, FAQ e tudo mais que você poderá utilizar para se conectar com nossos produtos.

# Footer About Section
about_footer: Copyright 2017 Avalara Inc. All rights reserved.

# Default post title
default_post_title: Home

# Default post cover index page (Recommended)
default_cover_index: "https://www.avalara.com/wp-content/uploads/2016/01/global-bg.svg"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: avalara
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/Avalara
facebook_url: https://www.facebook.com/avalara
github_url: https://github.com/Avalara